### ISSUE TITLE
Access to kivy3 on pypi

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy3#1]
@KeyWeeUsr can you give me and @tshirtman maintainer access to https://pypi.org/project/kivy3/ please?

Thanks in advance!

**Comment by KeyWeeUsr** [comment]
https://github.com/pypa/pypi-support/issues/407#issuecomment-633105580

**Comment by AndreMiras** [comment]
Thanks a lot, we could reclaim it, cheers :beers:
